services:
  mysql:
    image: mysql:8.0
    container_name: pisces_mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  pisces_api:
    build: ./api
    image: pisces:0.6
    restart: always
    volumes:
      - ./api:/app
    ports:
      - "9099:8080"
    depends_on:
      - mysql

  pisces_web:
    build: ./web
    image: pisces-web:0.6
    restart: always
    ports:
      - "8000:80"

  lightrag_eu:
    container_name: lightrag_eu
    image: lightrag:latest
    build:
      context: ./LightRAG
      dockerfile: Dockerfile.api
      tags:
        - lightrag:latest
    ports:
      - "9621:9621"
    volumes:
      - ./LightRAG/lightrag:/app/lightrag:delegated
      - ./LightRAG/data/rag_storage_eu:/app/data/rag_storage
      - ./LightRAG/data/inputs_eu:/app/data/inputs
      - ./LightRAG/config.ini:/app/config.ini
      - ./LightRAG/.env.eu:/app/.env
    env_file:
      - ./LightRAG/.env.eu
    restart: always

  lightrag_cn:
    container_name: lightrag_cn
    image: lightrag:latest
    ports:
      - "9622:9622"
    volumes:
      - ./LightRAG/lightrag:/app/lightrag:delegated
      - ./LightRAG/data/rag_storage_cn:/app/data/rag_storage
      - ./LightRAG/data/inputs_cn:/app/data/inputs
      - ./LightRAG/config.ini:/app/config.ini
      - ./LightRAG/.env.cn:/app/.env
    env_file:
      - ./LightRAG/.env.cn
    restart: always
